- name: nginx
  format: "$time_iso\t$http_x_forwarded_for\t$remote_addr\t$request\t$server_port\t$status\t$body_bytes_sent\t$http_referer\t\"$http_user_agent\"\t$request_time\t$upstream_addr\t$upstream_status\t$upstream_response_time\t$http_host\t$http_cookie"
  source_files:
    - ./logs/access.log
  static_labels:
    region: qa
  relabel_config:
    source_labels:
      - http_host
      - request
      - status
      - request_time
      - upstream_addr
      - upstream_response_time
    replacement:
      request:
        trim: "?"
      status:
        replaces:
          - target: 4.+
            value: 4xx
          - target: 5.+
            value: 5xx
  histogram_buckets: [0.1, 0.3, 0.5, 1, 2]